/*------------------------------------------------------------------------------
 * Title : OEM_DIMM.H
 * Author: Ken Lee
 *----------------------------------------------------------------------------*/


#ifndef	OEM_DIMM_H
#define	OEM_DIMM_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void S3S4S5toS0_OEM_DIMM(void);
extern void VerifyDimmerFunction(void);
extern void SW_DIMM_Function_AllLedsoff(void);


#endif	/* OEM_DIMM_H */

