/*------------------------------------------------------------------------------
 * Title : OEM_BANK2_FUNC.H
 * Author: Dino
 * Note  : These functions are for reference only. Please follow your
 *         project software specification to do some modification.
 *----------------------------------------------------------------------------*/


#ifndef	OEM_BANK2_FUNC_H
#define	OEM_BANK2_FUNC_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void Bank2_Test(void);


#endif	/* OEM_BANK2_FUNC_H */

