/*------------------------------------------------------------------------------
 * Title : OEM_MOTIONLED.H
 * Author: Ken Lee
 *----------------------------------------------------------------------------*/


#ifndef	OEM_MOTIONLED_H
#define	OEM_MOTIONLED_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void EnableMotionLedsFunction(void);
extern void MotionLedsFunctionNUMon(void);
extern void MotionLedsFunctionSCRon(void);
extern void MotionLedsFunctionCAPSon(void);
extern void MotionLedsFunctionAllLedson(void);
extern void MotionLedsFunctionAllLedsoff(void);
extern void MotionLedsFunctionCAPSonNUMon(void);
extern void NECP_MotionLedsFunction(void);


#endif	/* OEM_MOTIONLED_H */

