/*------------------------------------------------------------------------------
 * Title : OEM_HOSTIF.H
 * Author: Dino
 * Note  : These functions are for reference only. Please follow your
 *         project software specification to do some modification.
 *----------------------------------------------------------------------------*/


#ifndef	OEM_HOSTIF_H
#define	OEM_HOSTIF_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void InitSio(void);
extern void InitSysMemory2ECRam(void);


#endif	/* OEM_HOSTIF_H */

