/*------------------------------------------------------------------------------
 * Title : OEM_INCLUDE.H
 * Author: Dino
 * Note  : These functions are for reference only. Please follow your
 *         project software specification to do some modification.
 *----------------------------------------------------------------------------*/


#ifndef	OEM_INCLUDE_H
#define	OEM_INCLUDE_H


#include <OEM_Project.H>
#include <OEM_GPIO.H>
#include <OEM_INIT.H>
#include <OEM_MAIN.H>
#include <OEM_LED.H>
#include <OEM_FAN.H>
#include <OEM_BATTERY.H>
#include <OEM_MEMORY.H>
#include <OEM_SCANTABS.H>
#include <OEM_ACPI.H>
#include <OEM_CIR.H>
#include <OEM_FLASH.H>
#include <OEM_HOSTIF.H>
#include <OEM_6064.H>
#include <OEM_Ver.H>
#include <OEM_NECP.H>
#include <OEM_PORT686C.H>
#include <OEM_PECI.H>
#include <OEM_PM3.H>
#include <OEM_LPC.H>
#include <OEM_SPI.H>
#include <OEM_BANK1_Func.H>
#include <OEM_BANK2_Func.H>
#include <OEM_BANK3_Func.H>
#include <OEM_THERM.H>
#include <OEM_IPOD.H>
#include <OEM_TP.H>
#include <OEM_MotionLed.H>
#include <OEM_VICMV.H>
#include <OEM_DCMI.H>
#include <OEM_VICMVACDC.H>
#include <OEM_DIMM.H>
#include <OEM_S4S5WDG.H>
#include <OEM_Calpella.H>
#include <OEM_IT7230_SETTING.H>
#include <OEM_IT7230.H>
#include <OEM_EMI_SETTING.H>

#endif	/* OEM_INCLUDE_H */

