/*------------------------------------------------------------------------------
 * Title : OEM_BANK3_FUNC.H
 * Author: Dino
 * Note  : These functions are for reference only. Please follow your
 *         project software specification to do some modification.
 *----------------------------------------------------------------------------*/


#ifndef	OEM_BANK3_FUNC_H
#define	OEM_BANK3_FUNC_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void Bank3_Test(void);


#endif	/* OEM_BANK3_FUNC_H */

