/*------------------------------------------------------------------------------
 * Title : OEM_S4S5WDG.H
 * Author: Ken Lee
 *----------------------------------------------------------------------------*/


#ifndef	OEM_S4S5WDG_H
#define	OEM_S4S5WDG_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void WatchDOGS4S5_Resume(void);
extern void ResetSysOff_ECcmd_S4S5WDG(void);
extern void ResetSysOff_ECcmd_S4S5WDG1(void);
extern void DoTurnOffPower_668C_S4S5WDG(void);


#endif	/* OEM_S4S5WDG_H */

