/*------------------------------------------------------------------------------
 * Title : OEM_LPC.H
 * Author: Dino
 * Note  : These functions are for reference only.
 *----------------------------------------------------------------------------*/


#ifndef	OEM_LPC_H
#define	OEM_LPC_H


//------------------------------------------------------------------------------
// External Function Declaration
//------------------------------------------------------------------------------
extern void HLPC_WriteProtect0(void);
extern void HLPC_WriteProtectEnable0(void);


#endif	/* OEM_LPC_H */

