/*------------------------------------------------------------------------------
 * Title : CORE_INCLUDE.H
 * Author: Dino
 * Note  : These functions are for reference only. Please follow your
 *         project software specification to do some modification.
 *----------------------------------------------------------------------------*/

#ifndef	CORE_INCLUDE_H
#define	CORE_INCLUDE_H

#include <CORE_MAIN.H>
#include <CORE_TYPES.H>
#include <CORE_Memory.H>
#include <CORE_PS2.H>
#include <CORE_HOSTIF.H>
#include <CORE_SCAN.H>
#include <CORE_TIMERS.H>
#include <CORE_SCAN.H>
#include <CORE_SMBUS.H>
#include <CORE_ACPI.H>
#include <CORE_XLT.H>
#include <CORE_CHIPREGS.H>
#include <CORE_PORT6064.H>
#include <CORE_CHIPSFR.H>
#include <CORE_FLASH.H>
#include <CORE_CIR.H>
#include <CORE_IRQ.H>
#include <CORE_HSPI.H>
#include <CORE_PECI.H>
#include <CORE_BITADDR.H>
#include <CORE_SPI.H>
#include <CORE_LPC.H>

#include <intrins.h>
#include <stdio.h>

#endif	/* CORE_INCLUDE_H */

